# Generated by Django 3.2 on 2021-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.FileField(null=True, upload_to='sevices/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(null=True, upload_to='works/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(null=True, upload_to='works/%Y/%m/%d'),
        ),
    ]
