# Generated by Django 3.2 on 2021-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0003_alter_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
