# Generated by Django 3.2 on 2021-04-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0005_auto_20210427_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
    ]
