# Generated by Django 3.2 on 2021-04-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0007_auto_20210427_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='video',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
