# Generated by Django 3.2 on 2021-04-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0008_auto_20210427_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
    ]
