# Generated by Django 3.2 on 2021-04-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelperfectpost', '0010_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='works/%Y/%m/%d'),
        ),
    ]
